/**
 * RULE-BASED KEYWORD SEED
 */

const KEYWORD_RULES = {

  // Topik utama
  subjects: [
    "cuaca",
    "iklim",
    "berita",
    "informasi",
    "pengetahuan",
    "fakta",
    "data",
    "sejarah",
    "fenomena",
    "peristiwa",
    "kejadian",
    "tren",
    "perkembangan",
    "update",
    "kondisi",
    "situasi",
    "harga",
    "nilai",
    "kurs",
    "inflasi",
    "ekonomi",
    "keuangan",
    "bisnis",
    "pasar",
    "investasi",
    "kesehatan",
    "nutrisi",
    "gizi",
    "pola hidup",
    "gaya hidup",
    "kebiasaan",
    "kualitas hidup",
    "pendidikan",
    "pembelajaran",
    "materi",
    "konsep",
    "teori",
    "prinsip",
    "dasar",
    "pengertian",
    "teknologi",
    "digital",
    "internet",
    "komputer",
    "perangkat",
    "sistem",
    "aplikasi",
    "software",
    "lingkungan",
    "alam",
    "cuaca ekstrem",
    "perubahan iklim"
  ],

  // Objek / konteks tambahan
  objects: [
    "hari ini",
    "minggu ini",
    "bulan ini",
    "tahun ini",
    "terbaru",
    "terkini",
    "lengkap",
    "ringkas",
    "singkat",
    "detail",
    "resmi",
    "umum",
    "di indonesia",
    "di asia",
    "di dunia",
    "secara global",
    "secara nasional",
    "untuk pemula",
    "untuk umum",
    "untuk pelajar",
    "untuk mahasiswa",
    "untuk masyarakat",
    "secara sederhana",
    "secara umum",
    "yang perlu diketahui",
    "yang sering ditanyakan"
  ],

  // Kata kerja (intent)
  verbs: [
    "cara",
    "tips",
    "panduan",
    "langkah",
    "metode",
    "strategi",
    "proses",
    "mengatasi",
    "menghindari",
    "memahami",
    "menjelaskan",
    "mempelajari",
    "menggunakan",
    "menerapkan",
    "perbedaan",
    "persamaan",
    "fungsi",
    "manfaat",
    "dampak",
    "pengaruh",
    "akibat"
  ],

  // Objek teknologi
  tech: [
    "windows 11",
    "windows",
    "android",
    "ios",
    "laptop",
    "komputer",
    "smartphone",
    "hp",
    "browser",
    "internet",
    "wifi",
    "jaringan",
    "cloud",
    "cloud computing",
    "ai",
    "kecerdasan buatan",
    "machine learning",
    "sistem informasi",
    "database",
    "keamanan data",
    "privasi digital"
  ],

  // Topik ringan / sehari-hari
  daily: [
    "aktivitas harian",
    "kebiasaan sehari hari",
    "rutinitas pagi",
    "rutinitas malam",
    "waktu luang",
    "produktivitas",
    "manajemen waktu",
    "keseimbangan hidup"
  ]
};
